### ISSUE TITLE
Don't commit your node_modules folder!

### ISSUE THREAD

**Issue by paulxuca** [kabirvirji/auto-commit#1]
node_modules is where the bulk of your dependency code lives, and as such doesn't need to be included. Resolve this by:

1) untracking the folder
2) create a .gitignore and add the node_modules folder
3) commit the .gitignore file.

Let me know if you need any help!

**Comment by kshvmdn** [comment]
Or better yet, use GitHub's [recommended .gitignore for Node](https://github.com/github/gitignore/blob/master/Node.gitignore), on top of node_modules, it'll ignore a bunch of other stuff that generally shouldn't be committed (like logs).

**Comment by kabirvirji** [comment]
Thanks!

https://github.com/kabirvirji/auto-commit/commit/97aff237390bb11e0ed0108487fb94539f24d9a8
